doctrine:
    dbal:
        url: '%env(DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        server_version: '17'

        profiling_collect_backtrace: '%kernel.debug%'
    orm:
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        identity_generation_preferences:
            Doctrine\DBAL\Platforms\PostgreSQLPlatform: identity
        auto_mapping: false
        mappings:
            Auth:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Auth/Entity'
                prefix: 'App\Auth\Entity'
                alias: Auth
            Bitacora:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Bitacora/Domain/Entity'
                prefix: 'App\Bitacora\Domain\Entity'
                alias: Bitacora
            Gestion:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Gestion/Domain/Entity'
                prefix: 'App\Gestion\Domain\Entity'
                alias: Gestion
            Carrera:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Academico/Carrera/Domain/Entity'
                prefix: 'App\Academico\Carrera\Domain\Entity'
                alias: Carrera
            Materia:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Academico/Materia/Domain/Entity'
                prefix: 'App\Academico\Materia\Domain\Entity'
                alias: Materia
            Aula:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Academico/Aula/Domain/Entity'
                prefix: 'App\Academico\Aula\Domain\Entity'
                alias: Aula
            Turno:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Academico/Turno/Domain/Entity'
                prefix: 'App\Academico\Turno\Domain\Entity'
                alias: Turno
            Grupo:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Academico/Grupo/Domain/Entity'
                prefix: 'App\Academico\Grupo\Domain\Entity'
                alias: Grupo
            Horario:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Academico/Horario/Domain/Entity'
                prefix: 'App\Academico\Horario\Domain\Entity'
                alias: Horario
            Inscripcion:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Inscripcion/Domain/Entity'
                prefix: 'App\Inscripcion\Domain\Entity'
                alias: Inscripcion
            Usuario:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Usuario/Domain/Entity'
                prefix: 'App\Usuario\Domain\Entity'
                alias: Usuario
            Notas:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Notas/Domain/Entity'
                prefix: 'App\Notas\Domain\Entity'
                alias: Notas

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
