# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'

    # Note that the session will be started ONLY if you read or write from it.
    session:
        cookie_lifetime: 0       # 0 = la cookie muere al cerrar el navegador
        cookie_secure: auto      # secure cuando se sirve por HTTPS
        cookie_samesite: lax     # protección extra contra CSRF

    #esi: true
    #fragments: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
