twig:
    default_path: '%kernel.project_dir%/templates'
    file_name_pattern: '*.twig'
    paths:
        '%kernel.project_dir%/src/Auth/UI/View': auth

when@test:
    twig:
        strict_variables: true
