twig:
    default_path: '%kernel.project_dir%/templates'
    file_name_pattern: '*.twig'
    paths:
        '%kernel.project_dir%/src/Auth/UI/View': auth
        '%kernel.project_dir%/src/Home/UI/View': home
        '%kernel.project_dir%/src/Bitacora/UI/View': bitacora

when@test:
    twig:
        strict_variables: true
