<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Grupos en Notas:
 * - notas_docente_materia ahora incluye grupo (docente dicta materia a un grupo).
 * - notas_inscripcion_grupo: asignación de cada estudiante a un grupo por materia.
 */
final class Version20260613150000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Agregar grupo a asignacion de docentes y crear asignacion estudiante-grupo por materia';
    }

    public function up(Schema $schema): void
    {
        // notas_docente_materia: añadir grupo y reemplazar la unicidad (gestion,materia) por (gestion,materia,grupo).
        $this->addSql('DROP INDEX uniq_docente_materia_gestion');
        $this->addSql('ALTER TABLE notas_docente_materia ADD grupo_id INT NOT NULL');
        $this->addSql('ALTER TABLE notas_docente_materia ADD CONSTRAINT fk_notas_dm_grupo FOREIGN KEY (grupo_id) REFERENCES grupos (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_notas_dm_grupo ON notas_docente_materia (grupo_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_docente_materia_grupo ON notas_docente_materia (gestion_id, materia_id, grupo_id)');

        // notas_inscripcion_grupo: estudiante -> grupo, por materia.
        $this->addSql('CREATE TABLE notas_inscripcion_grupo (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            inscripcion_id INT NOT NULL,
            materia_id INT NOT NULL,
            grupo_id INT NOT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_inscripcion_materia_grupo ON notas_inscripcion_grupo (inscripcion_id, materia_id)');
        $this->addSql('CREATE INDEX idx_nig_grupo_materia ON notas_inscripcion_grupo (grupo_id, materia_id)');
        $this->addSql('ALTER TABLE notas_inscripcion_grupo ADD CONSTRAINT fk_nig_inscripcion FOREIGN KEY (inscripcion_id) REFERENCES inscripciones (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE notas_inscripcion_grupo ADD CONSTRAINT fk_nig_materia FOREIGN KEY (materia_id) REFERENCES materias (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE notas_inscripcion_grupo ADD CONSTRAINT fk_nig_grupo FOREIGN KEY (grupo_id) REFERENCES grupos (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE notas_inscripcion_grupo DROP CONSTRAINT fk_nig_inscripcion');
        $this->addSql('ALTER TABLE notas_inscripcion_grupo DROP CONSTRAINT fk_nig_materia');
        $this->addSql('ALTER TABLE notas_inscripcion_grupo DROP CONSTRAINT fk_nig_grupo');
        $this->addSql('DROP TABLE notas_inscripcion_grupo');

        $this->addSql('DROP INDEX uniq_docente_materia_grupo');
        $this->addSql('DROP INDEX idx_notas_dm_grupo');
        $this->addSql('ALTER TABLE notas_docente_materia DROP CONSTRAINT fk_notas_dm_grupo');
        $this->addSql('ALTER TABLE notas_docente_materia DROP grupo_id');
        $this->addSql('CREATE UNIQUE INDEX uniq_docente_materia_gestion ON notas_docente_materia (gestion_id, materia_id)');
    }
}
