<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260613120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create user role and permission management module';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('ALTER TABLE users ADD active BOOLEAN DEFAULT true NOT NULL');
        $this->addSql('ALTER TABLE users ADD updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');

        $this->addSql('CREATE TABLE permissions (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            code VARCHAR(120) NOT NULL,
            module VARCHAR(80) NOT NULL,
            action VARCHAR(80) NOT NULL,
            description VARCHAR(180) NOT NULL,
            active BOOLEAN DEFAULT true NOT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_permissions_code ON permissions (code)');

        $this->addSql('CREATE TABLE roles (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            name VARCHAR(80) NOT NULL,
            description TEXT DEFAULT NULL,
            active BOOLEAN DEFAULT true NOT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
            PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_roles_name ON roles (name)');

        $this->addSql('CREATE TABLE role_permissions (
            role_id INT NOT NULL,
            permission_id INT NOT NULL,
            PRIMARY KEY(role_id, permission_id))');
        $this->addSql('CREATE INDEX idx_role_permissions_role ON role_permissions (role_id)');
        $this->addSql('CREATE INDEX idx_role_permissions_permission ON role_permissions (permission_id)');
        $this->addSql('ALTER TABLE role_permissions ADD CONSTRAINT fk_role_permissions_role FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE role_permissions ADD CONSTRAINT fk_role_permissions_permission FOREIGN KEY (permission_id) REFERENCES permissions (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE user_roles (
            user_id INT NOT NULL,
            role_id INT NOT NULL,
            PRIMARY KEY(user_id, role_id))');
        $this->addSql('CREATE INDEX idx_user_roles_user ON user_roles (user_id)');
        $this->addSql('CREATE INDEX idx_user_roles_role ON user_roles (role_id)');
        $this->addSql('ALTER TABLE user_roles ADD CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_roles ADD CONSTRAINT fk_user_roles_role FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->seedPermissions();
        $this->seedRoles();
        $this->assignAdministratorPermissions();
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE user_roles DROP CONSTRAINT fk_user_roles_user');
        $this->addSql('ALTER TABLE user_roles DROP CONSTRAINT fk_user_roles_role');
        $this->addSql('ALTER TABLE role_permissions DROP CONSTRAINT fk_role_permissions_role');
        $this->addSql('ALTER TABLE role_permissions DROP CONSTRAINT fk_role_permissions_permission');
        $this->addSql('DROP TABLE user_roles');
        $this->addSql('DROP TABLE role_permissions');
        $this->addSql('DROP TABLE roles');
        $this->addSql('DROP TABLE permissions');
        $this->addSql('ALTER TABLE users DROP updated_at');
        $this->addSql('ALTER TABLE users DROP active');
    }

    private function seedPermissions(): void
    {
        $now = (new \DateTimeImmutable('now', new \DateTimeZone('America/La_Paz')))->format('Y-m-d H:i:s');
        $permissions = [
            ['usuarios.ver', 'Usuarios', 'Ver', 'Ver usuarios'],
            ['usuarios.crear', 'Usuarios', 'Crear', 'Crear usuarios'],
            ['usuarios.editar', 'Usuarios', 'Editar', 'Editar usuarios'],
            ['usuarios.estado', 'Usuarios', 'Estado', 'Activar o desactivar usuarios'],
            ['usuarios.reset', 'Usuarios', 'Reset', 'Enviar recuperacion de contrasena'],
            ['roles.ver', 'Roles y permisos', 'Ver', 'Ver roles'],
            ['roles.crear', 'Roles y permisos', 'Crear', 'Crear roles'],
            ['roles.editar', 'Roles y permisos', 'Editar', 'Editar roles y permisos'],
            ['roles.estado', 'Roles y permisos', 'Estado', 'Activar o desactivar roles'],
            ['gestion.ver', 'Gestion CUP', 'Ver', 'Ver gestiones CUP'],
            ['gestion.crear', 'Gestion CUP', 'Crear', 'Crear gestiones CUP'],
            ['gestion.editar', 'Gestion CUP', 'Editar', 'Editar parametros y cronograma'],
            ['gestion.activar', 'Gestion CUP', 'Activar', 'Activar gestion CUP'],
            ['academico.ver', 'Administracion academica', 'Ver', 'Ver catalogos academicos'],
            ['academico.crear', 'Administracion academica', 'Crear', 'Crear catalogos academicos'],
            ['academico.editar', 'Administracion academica', 'Editar', 'Editar catalogos academicos'],
            ['academico.estado', 'Administracion academica', 'Estado', 'Activar o desactivar catalogos academicos'],
            ['bitacora.ver', 'Bitacora', 'Ver', 'Consultar bitacora'],
            ['inscripciones.ver', 'Inscripciones', 'Ver', 'Ver inscripciones CUP'],
            ['inscripciones.validar', 'Inscripciones', 'Validar', 'Validar documentos e inscripciones'],
        ];

        foreach ($permissions as [$code, $module, $action, $description]) {
            $this->addSql(sprintf(
                "INSERT INTO permissions (code, module, action, description, active, created_at) VALUES ('%s', '%s', '%s', '%s', true, '%s')",
                $code,
                str_replace("'", "''", $module),
                str_replace("'", "''", $action),
                str_replace("'", "''", $description),
                $now,
            ));
        }
    }

    private function seedRoles(): void
    {
        $now = (new \DateTimeImmutable('now', new \DateTimeZone('America/La_Paz')))->format('Y-m-d H:i:s');

        $this->addSql("INSERT INTO roles (name, description, active, created_at) VALUES ('Administrador', 'Control total del sistema CUP.', true, '$now')");
        $this->addSql("INSERT INTO roles (name, description, active, created_at) VALUES ('Coordinador', 'Gestion academica, cronograma, grupos y reportes.', true, '$now')");
        $this->addSql("INSERT INTO roles (name, description, active, created_at) VALUES ('Postulante', 'Acceso basico a inscripcion y perfil.', true, '$now')");
    }

    private function assignAdministratorPermissions(): void
    {
        $this->addSql("INSERT INTO role_permissions (role_id, permission_id)
            SELECT r.id, p.id
            FROM roles r
            CROSS JOIN permissions p
            WHERE r.name = 'Administrador'");

        $this->addSql("INSERT INTO role_permissions (role_id, permission_id)
            SELECT r.id, p.id
            FROM roles r
            JOIN permissions p ON p.code IN (
                'gestion.ver', 'gestion.crear', 'gestion.editar', 'gestion.activar',
                'academico.ver', 'academico.crear', 'academico.editar', 'academico.estado',
                'bitacora.ver', 'inscripciones.ver', 'inscripciones.validar'
            )
            WHERE r.name = 'Coordinador'");

        $this->addSql("INSERT INTO role_permissions (role_id, permission_id)
            SELECT r.id, p.id
            FROM roles r
            JOIN permissions p ON p.code IN ('inscripciones.ver')
            WHERE r.name = 'Postulante'");
    }
}
