<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260612170000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add otros field to inscripciones + create inscripcion_documentos table';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('ALTER TABLE inscripciones ADD otros TEXT DEFAULT NULL');

        $this->addSql('CREATE TABLE inscripcion_documentos (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            inscripcion_id INT NOT NULL,
            nombre VARCHAR(80) NOT NULL,
            archivo_ruta VARCHAR(255) NOT NULL,
            archivo_extension VARCHAR(20) NOT NULL,
            archivo_tamanio INT NOT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_documentos_inscripcion ON inscripcion_documentos (inscripcion_id)');
        $this->addSql('ALTER TABLE inscripcion_documentos ADD CONSTRAINT fk_documentos_inscripcion FOREIGN KEY (inscripcion_id) REFERENCES inscripciones (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE inscripcion_documentos DROP CONSTRAINT fk_documentos_inscripcion');
        $this->addSql('DROP TABLE inscripcion_documentos');
        $this->addSql('ALTER TABLE inscripciones DROP otros');
    }
}
