<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260612160000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create inscripciones table';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE inscripciones (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            user_id INT NOT NULL,
            gestion_id INT NOT NULL,
            carrera_id INT NOT NULL,
            ci VARCHAR(20) NOT NULL,
            nombres VARCHAR(120) NOT NULL,
            apellidos VARCHAR(120) NOT NULL,
            fecha_nacimiento TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            sexo VARCHAR(1) NOT NULL,
            direccion TEXT DEFAULT NULL,
            telefono VARCHAR(20) DEFAULT NULL,
            email VARCHAR(180) NOT NULL,
            colegio_procedencia VARCHAR(120) DEFAULT NULL,
            ciudad VARCHAR(80) DEFAULT NULL,
            titulo_bachiller BOOLEAN DEFAULT false NOT NULL,
            turno_preferencia VARCHAR(20) DEFAULT NULL,
            estado VARCHAR(20) NOT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_inscripciones_user_gestion ON inscripciones (user_id, gestion_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_inscripciones_ci ON inscripciones (ci)');
        $this->addSql('CREATE INDEX idx_inscripciones_gestion ON inscripciones (gestion_id)');
        $this->addSql('CREATE INDEX idx_inscripciones_estado ON inscripciones (estado)');
        $this->addSql('ALTER TABLE inscripciones ADD CONSTRAINT fk_inscripciones_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE inscripciones ADD CONSTRAINT fk_inscripciones_gestion FOREIGN KEY (gestion_id) REFERENCES gestiones (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE inscripciones ADD CONSTRAINT fk_inscripciones_carrera FOREIGN KEY (carrera_id) REFERENCES carreras (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE inscripciones DROP CONSTRAINT fk_inscripciones_user');
        $this->addSql('ALTER TABLE inscripciones DROP CONSTRAINT fk_inscripciones_gestion');
        $this->addSql('ALTER TABLE inscripciones DROP CONSTRAINT fk_inscripciones_carrera');
        $this->addSql('DROP TABLE inscripciones');
    }
}
