<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Pagos del arancel de inscripcion via pasarela (Stripe Checkout).
 */
final class Version20260614150000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Crear tabla pagos (arancel de inscripcion via Stripe)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE pagos (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            inscripcion_id INT NOT NULL,
            user_id INT NOT NULL,
            email VARCHAR(180) NOT NULL,
            amount INT NOT NULL,
            currency VARCHAR(3) NOT NULL,
            estado VARCHAR(16) NOT NULL,
            provider VARCHAR(20) NOT NULL,
            stripe_session_id VARCHAR(255) DEFAULT NULL,
            stripe_payment_intent_id VARCHAR(255) DEFAULT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            paid_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
            PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_pagos_inscripcion ON pagos (inscripcion_id)');
        $this->addSql('CREATE INDEX idx_pagos_estado ON pagos (estado)');
        $this->addSql('CREATE INDEX idx_pagos_stripe_session ON pagos (stripe_session_id)');
        $this->addSql('ALTER TABLE pagos ADD CONSTRAINT fk_pagos_inscripcion FOREIGN KEY (inscripcion_id) REFERENCES inscripciones (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE pagos DROP CONSTRAINT fk_pagos_inscripcion');
        $this->addSql('DROP TABLE pagos');
    }
}
