<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260602110000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create carreras catalog and link gestion carreras to it';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE carreras (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, codigo VARCHAR(30) NOT NULL, nombre VARCHAR(160) NOT NULL, descripcion TEXT DEFAULT NULL, facultad VARCHAR(120) DEFAULT NULL, modalidad VARCHAR(80) DEFAULT NULL, estado VARCHAR(20) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_carreras_codigo ON carreras (codigo)');
        $this->addSql('CREATE INDEX idx_carreras_estado ON carreras (estado)');
        $this->addSql('ALTER TABLE gestion_carreras DROP COLUMN IF EXISTS carrera_nombre');
        $this->addSql('ALTER TABLE gestion_carreras ADD CONSTRAINT FK_GESTION_CARRERAS_CARRERA FOREIGN KEY (carrera_id) REFERENCES carreras (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE gestion_carreras DROP CONSTRAINT IF EXISTS FK_GESTION_CARRERAS_CARRERA');
        $this->addSql('ALTER TABLE gestion_carreras ADD carrera_nombre VARCHAR(140) DEFAULT \'Carrera migrada\' NOT NULL');
        $this->addSql('DROP TABLE carreras');
    }
}
