<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260530070000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create log entries table for Bitacora module';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE log_entries (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT DEFAULT NULL, user_label VARCHAR(180) NOT NULL, action VARCHAR(60) NOT NULL, module VARCHAR(80) NOT NULL, description TEXT NOT NULL, level VARCHAR(16) NOT NULL, ip VARCHAR(45) DEFAULT NULL, user_agent VARCHAR(255) DEFAULT NULL, metadata JSON DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_log_entries_user ON log_entries (user_id)');
        $this->addSql('CREATE INDEX idx_log_entries_action ON log_entries (action)');
        $this->addSql('CREATE INDEX idx_log_entries_module ON log_entries (module)');
        $this->addSql('CREATE INDEX idx_log_entries_created_at ON log_entries (created_at)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE log_entries');
    }
}
