<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260613130000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create notas module: notas, notas_docente_materia, permisos notas.* y rol Docente';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE notas_docente_materia (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            gestion_id INT NOT NULL,
            materia_id INT NOT NULL,
            docente_id INT NOT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_docente_materia_gestion ON notas_docente_materia (gestion_id, materia_id)');
        $this->addSql('CREATE INDEX idx_notas_dm_docente ON notas_docente_materia (docente_id)');
        $this->addSql('ALTER TABLE notas_docente_materia ADD CONSTRAINT fk_notas_dm_gestion FOREIGN KEY (gestion_id) REFERENCES gestiones (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE notas_docente_materia ADD CONSTRAINT fk_notas_dm_materia FOREIGN KEY (materia_id) REFERENCES materias (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE notas_docente_materia ADD CONSTRAINT fk_notas_dm_docente FOREIGN KEY (docente_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE notas (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            inscripcion_id INT NOT NULL,
            materia_id INT NOT NULL,
            numero_examen INT NOT NULL,
            valor INT NOT NULL,
            observacion TEXT DEFAULT NULL,
            registrada_por_id INT DEFAULT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
            PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_nota_inscripcion_materia_examen ON notas (inscripcion_id, materia_id, numero_examen)');
        $this->addSql('CREATE INDEX idx_notas_materia ON notas (materia_id)');
        $this->addSql('CREATE INDEX idx_notas_inscripcion ON notas (inscripcion_id)');
        $this->addSql('ALTER TABLE notas ADD CONSTRAINT fk_notas_inscripcion FOREIGN KEY (inscripcion_id) REFERENCES inscripciones (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE notas ADD CONSTRAINT fk_notas_materia FOREIGN KEY (materia_id) REFERENCES materias (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE notas ADD CONSTRAINT fk_notas_registrada_por FOREIGN KEY (registrada_por_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->seedPermissions();
        $this->seedDocenteRole();
        $this->assignPermissions();
    }

    public function down(Schema $schema): void
    {
        $this->addSql("DELETE FROM role_permissions WHERE permission_id IN (SELECT id FROM permissions WHERE code IN ('notas.ver', 'notas.registrar', 'notas.asignar'))");
        $this->addSql("DELETE FROM role_permissions WHERE role_id IN (SELECT id FROM roles WHERE name = 'Docente')");
        $this->addSql("DELETE FROM user_roles WHERE role_id IN (SELECT id FROM roles WHERE name = 'Docente')");
        $this->addSql("DELETE FROM roles WHERE name = 'Docente'");
        $this->addSql("DELETE FROM permissions WHERE code IN ('notas.ver', 'notas.registrar', 'notas.asignar')");

        $this->addSql('ALTER TABLE notas DROP CONSTRAINT fk_notas_inscripcion');
        $this->addSql('ALTER TABLE notas DROP CONSTRAINT fk_notas_materia');
        $this->addSql('ALTER TABLE notas DROP CONSTRAINT fk_notas_registrada_por');
        $this->addSql('DROP TABLE notas');

        $this->addSql('ALTER TABLE notas_docente_materia DROP CONSTRAINT fk_notas_dm_gestion');
        $this->addSql('ALTER TABLE notas_docente_materia DROP CONSTRAINT fk_notas_dm_materia');
        $this->addSql('ALTER TABLE notas_docente_materia DROP CONSTRAINT fk_notas_dm_docente');
        $this->addSql('DROP TABLE notas_docente_materia');
    }

    private function seedPermissions(): void
    {
        $now = (new \DateTimeImmutable('now', new \DateTimeZone('America/La_Paz')))->format('Y-m-d H:i:s');
        $permissions = [
            ['notas.ver', 'Notas', 'Ver', 'Ver notas y boletines'],
            ['notas.registrar', 'Notas', 'Registrar', 'Registrar y editar notas'],
            ['notas.asignar', 'Notas', 'Asignar', 'Asignar docentes a materias'],
        ];

        foreach ($permissions as [$code, $module, $action, $description]) {
            $this->addSql(sprintf(
                "INSERT INTO permissions (code, module, action, description, active, created_at) VALUES ('%s', '%s', '%s', '%s', true, '%s')",
                $code,
                $module,
                $action,
                $description,
                $now,
            ));
        }
    }

    private function seedDocenteRole(): void
    {
        $now = (new \DateTimeImmutable('now', new \DateTimeZone('America/La_Paz')))->format('Y-m-d H:i:s');
        $this->addSql("INSERT INTO roles (name, description, active, created_at) VALUES ('Docente', 'Carga y consulta de notas de sus materias asignadas.', true, '$now')");
    }

    private function assignPermissions(): void
    {
        // Administrador: todos los permisos de notas.
        $this->addSql("INSERT INTO role_permissions (role_id, permission_id)
            SELECT r.id, p.id
            FROM roles r
            JOIN permissions p ON p.code IN ('notas.ver', 'notas.registrar', 'notas.asignar')
            WHERE r.name = 'Administrador'");

        // Coordinador: ver y asignar docentes.
        $this->addSql("INSERT INTO role_permissions (role_id, permission_id)
            SELECT r.id, p.id
            FROM roles r
            JOIN permissions p ON p.code IN ('notas.ver', 'notas.asignar')
            WHERE r.name = 'Coordinador'");

        // Docente: ver y registrar notas.
        $this->addSql("INSERT INTO role_permissions (role_id, permission_id)
            SELECT r.id, p.id
            FROM roles r
            JOIN permissions p ON p.code IN ('notas.ver', 'notas.registrar')
            WHERE r.name = 'Docente'");
    }
}
