<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Acta de control de recepcion de documentos: por cada requisito documental
 * (RequisitoCatalog) de una postulacion, la administracion registra si el
 * postulante lo entrego, lo observo o no lo presento el dia de la cita.
 */
final class Version20260614130000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Crear inscripcion_verificaciones (acta de control de recepcion de documentos)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql("CREATE TABLE inscripcion_verificaciones (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            inscripcion_id INT NOT NULL,
            requisito_codigo VARCHAR(40) NOT NULL,
            estado VARCHAR(20) DEFAULT 'PENDIENTE' NOT NULL,
            observacion TEXT DEFAULT NULL,
            verificado_por INT DEFAULT NULL,
            verificado_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
            PRIMARY KEY(id))");
        $this->addSql('CREATE UNIQUE INDEX uniq_verificacion_inscripcion_requisito ON inscripcion_verificaciones (inscripcion_id, requisito_codigo)');
        $this->addSql('CREATE INDEX idx_verificacion_inscripcion ON inscripcion_verificaciones (inscripcion_id)');
        $this->addSql('ALTER TABLE inscripcion_verificaciones ADD CONSTRAINT fk_verificacion_inscripcion FOREIGN KEY (inscripcion_id) REFERENCES inscripciones (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE inscripcion_verificaciones DROP CONSTRAINT fk_verificacion_inscripcion');
        $this->addSql('DROP TABLE inscripcion_verificaciones');
    }
}
