<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260602090000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create gestion academica module tables';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE gestiones (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, codigo VARCHAR(40) NOT NULL, nombre VARCHAR(140) NOT NULL, descripcion TEXT DEFAULT NULL, estado VARCHAR(40) NOT NULL, fecha_activacion TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, fecha_finalizacion TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, creado_por INT DEFAULT NULL, activado_por INT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_GESTIONES_CODIGO ON gestiones (codigo)');
        $this->addSql('CREATE INDEX idx_gestiones_estado ON gestiones (estado)');

        $this->addSql('CREATE TABLE gestion_configuraciones (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, gestion_id INT NOT NULL, cupo_total INT NOT NULL, max_estudiantes_por_grupo INT NOT NULL, max_grupos_por_docente INT NOT NULL, nota_minima_aprobacion INT NOT NULL, cantidad_examenes INT NOT NULL, permite_reinscripcion BOOLEAN DEFAULT false NOT NULL, permite_cambio_grupo BOOLEAN DEFAULT false NOT NULL, generar_bitacora BOOLEAN DEFAULT true NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_GESTION_CONFIGURACION ON gestion_configuraciones (gestion_id)');

        $this->addSql('CREATE TABLE gestion_periodos (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, gestion_id INT NOT NULL, tipo_periodo VARCHAR(40) NOT NULL, fecha_inicio DATE NOT NULL, fecha_fin DATE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_GESTION_PERIODOS_GESTION ON gestion_periodos (gestion_id)');
        $this->addSql('CREATE INDEX idx_gestion_periodos_tipo ON gestion_periodos (tipo_periodo)');

        $this->addSql('CREATE TABLE gestion_carreras (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, gestion_id INT NOT NULL, carrera_id INT NOT NULL, habilitada BOOLEAN DEFAULT true NOT NULL, cupo_carrera INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_gestion_carrera ON gestion_carreras (gestion_id, carrera_id)');

        $this->addSql('CREATE TABLE gestion_cupos (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, gestion_id INT NOT NULL, cupo_total INT NOT NULL, inscritos INT DEFAULT 0 NOT NULL, reservados INT DEFAULT 0 NOT NULL, disponibles INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_GESTION_CUPOS_GESTION ON gestion_cupos (gestion_id)');

        $this->addSql('CREATE TABLE gestion_historial (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, gestion_id INT NOT NULL, accion VARCHAR(60) NOT NULL, descripcion TEXT NOT NULL, usuario_id INT DEFAULT NULL, fecha TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_GESTION_HISTORIAL_GESTION ON gestion_historial (gestion_id)');
        $this->addSql('CREATE INDEX idx_gestion_historial_accion ON gestion_historial (accion)');

        $this->addSql('ALTER TABLE gestion_configuraciones ADD CONSTRAINT FK_GESTION_CONFIGURACION FOREIGN KEY (gestion_id) REFERENCES gestiones (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE gestion_periodos ADD CONSTRAINT FK_GESTION_PERIODOS FOREIGN KEY (gestion_id) REFERENCES gestiones (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE gestion_carreras ADD CONSTRAINT FK_GESTION_CARRERAS FOREIGN KEY (gestion_id) REFERENCES gestiones (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE gestion_cupos ADD CONSTRAINT FK_GESTION_CUPOS FOREIGN KEY (gestion_id) REFERENCES gestiones (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE gestion_historial ADD CONSTRAINT FK_GESTION_HISTORIAL FOREIGN KEY (gestion_id) REFERENCES gestiones (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE gestion_historial DROP CONSTRAINT FK_GESTION_HISTORIAL');
        $this->addSql('ALTER TABLE gestion_cupos DROP CONSTRAINT FK_GESTION_CUPOS');
        $this->addSql('ALTER TABLE gestion_carreras DROP CONSTRAINT FK_GESTION_CARRERAS');
        $this->addSql('ALTER TABLE gestion_periodos DROP CONSTRAINT FK_GESTION_PERIODOS');
        $this->addSql('ALTER TABLE gestion_configuraciones DROP CONSTRAINT FK_GESTION_CONFIGURACION');
        $this->addSql('DROP TABLE gestion_historial');
        $this->addSql('DROP TABLE gestion_cupos');
        $this->addSql('DROP TABLE gestion_carreras');
        $this->addSql('DROP TABLE gestion_periodos');
        $this->addSql('DROP TABLE gestion_configuraciones');
        $this->addSql('DROP TABLE gestiones');
    }
}
