<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260602120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create academic administration tables for materias, aulas, grupos and horarios';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE materias (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, codigo VARCHAR(30) NOT NULL, nombre VARCHAR(120) NOT NULL, descripcion TEXT DEFAULT NULL, estado VARCHAR(20) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_materias_codigo ON materias (codigo)');

        $this->addSql('CREATE TABLE aulas (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, codigo VARCHAR(30) NOT NULL, nombre VARCHAR(120) NOT NULL, piso INT NOT NULL, capacidad INT NOT NULL, ubicacion VARCHAR(160) DEFAULT NULL, estado VARCHAR(20) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_aulas_codigo ON aulas (codigo)');

        $this->addSql('CREATE TABLE grupos (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, gestion_id INT NOT NULL, codigo VARCHAR(30) NOT NULL, nombre VARCHAR(120) NOT NULL, cupo INT NOT NULL, inscritos_estimados INT DEFAULT 0 NOT NULL, estado VARCHAR(40) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_grupo_gestion_codigo ON grupos (gestion_id, codigo)');

        $this->addSql('CREATE TABLE horarios (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, grupo_id INT NOT NULL, materia_id INT NOT NULL, aula_id INT NOT NULL, dia VARCHAR(20) NOT NULL, hora_inicio TIME(0) WITHOUT TIME ZONE NOT NULL, hora_fin TIME(0) WITHOUT TIME ZONE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_HORARIOS_GRUPO ON horarios (grupo_id)');
        $this->addSql('CREATE INDEX IDX_HORARIOS_MATERIA ON horarios (materia_id)');
        $this->addSql('CREATE INDEX IDX_HORARIOS_AULA ON horarios (aula_id)');

        $this->addSql('ALTER TABLE grupos ADD CONSTRAINT FK_GRUPOS_GESTION FOREIGN KEY (gestion_id) REFERENCES gestiones (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE horarios ADD CONSTRAINT FK_HORARIOS_GRUPO FOREIGN KEY (grupo_id) REFERENCES grupos (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE horarios ADD CONSTRAINT FK_HORARIOS_MATERIA FOREIGN KEY (materia_id) REFERENCES materias (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE horarios ADD CONSTRAINT FK_HORARIOS_AULA FOREIGN KEY (aula_id) REFERENCES aulas (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE horarios DROP CONSTRAINT FK_HORARIOS_AULA');
        $this->addSql('ALTER TABLE horarios DROP CONSTRAINT FK_HORARIOS_MATERIA');
        $this->addSql('ALTER TABLE horarios DROP CONSTRAINT FK_HORARIOS_GRUPO');
        $this->addSql('ALTER TABLE grupos DROP CONSTRAINT FK_GRUPOS_GESTION');
        $this->addSql('DROP TABLE horarios');
        $this->addSql('DROP TABLE grupos');
        $this->addSql('DROP TABLE aulas');
        $this->addSql('DROP TABLE materias');
    }
}
