<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Crea el catalogo de turnos (plantilla de tiempo reutilizable) y siembra
 * los turnos base: Manana, Tarde y Noche.
 */
final class Version20260603120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create turnos catalog table and seed default turnos';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE turnos (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nombre VARCHAR(40) NOT NULL, hora_inicio TIME(0) WITHOUT TIME ZONE NOT NULL, hora_fin TIME(0) WITHOUT TIME ZONE NOT NULL, estado VARCHAR(20) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_turnos_nombre ON turnos (nombre)');

        $this->addSql("INSERT INTO turnos (nombre, hora_inicio, hora_fin, estado, created_at) VALUES ('MANANA', '07:00', '13:00', 'ACTIVO', NOW())");
        $this->addSql("INSERT INTO turnos (nombre, hora_inicio, hora_fin, estado, created_at) VALUES ('TARDE', '13:00', '19:00', 'ACTIVO', NOW())");
        $this->addSql("INSERT INTO turnos (nombre, hora_inicio, hora_fin, estado, created_at) VALUES ('NOCHE', '18:30', '21:30', 'ACTIVO', NOW())");
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE turnos');
    }
}
