<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Calendario de revision de documentos: dias habiles por gestion con capacidad.
 * Permite el agendamiento automatico de la cita al presentar una postulacion.
 */
final class Version20260614140000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Crear inscripcion_calendario_revision (dias habiles + capacidad para auto-agendar la cita)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE inscripcion_calendario_revision (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            gestion_id INT NOT NULL,
            fecha DATE NOT NULL,
            capacidad INT NOT NULL,
            agendados INT DEFAULT 0 NOT NULL,
            habilitado BOOLEAN DEFAULT true NOT NULL,
            PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_calendario_gestion_fecha ON inscripcion_calendario_revision (gestion_id, fecha)');
        $this->addSql('CREATE INDEX idx_calendario_gestion ON inscripcion_calendario_revision (gestion_id)');
        $this->addSql('ALTER TABLE inscripcion_calendario_revision ADD CONSTRAINT fk_calendario_gestion FOREIGN KEY (gestion_id) REFERENCES gestiones (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE inscripcion_calendario_revision DROP CONSTRAINT fk_calendario_gestion');
        $this->addSql('DROP TABLE inscripcion_calendario_revision');
    }
}
